language: node_js
node_js:
  - 4.1
before_script:
  - "curl -O http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.0.jar"
  - "npm install"
  - "npm run build"
  - "java -jar selenium-server-standalone-2.53.0.jar -Dphantomjs.binary.path=./node_modules/phantomjs-prebuilt/bin/phantomjs &"
  - sleep 3
  - npm start &
  - sleep 5
script:
  - wdio ./test/wdio.conf.js  
